# Generated by Django 4.2.7 on 2026-02-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('auditor', 'Auditor'), ('manufacturer', 'Manufacturer')], max_length=20),
        ),
    ]
