# Generated by Django 4.2.7 on 2026-02-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farmer_id', models.IntegerField()),
                ('batch_id', models.CharField(max_length=100)),
                ('herb', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('location', models.CharField(max_length=255)),
                ('previous_hash', models.CharField(max_length=256)),
                ('hash', models.CharField(max_length=256)),
            ],
        ),
    ]
