# Generated by Django 4.2.7 on 2026-02-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='auditor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='block_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='manufacturer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='processing_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='farmer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='block',
            name='herb',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='index',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='previous_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='block',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
